export const ADMIN_APPOINTMENT_CREATE_REQUEST = "ADMIN_APPOINTMENT_CREATE_REQUEST";
export const ADMIN_APPOINTMENT_CREATE_SUCCESS = "ADMIN_APPOINTMENT_CREATE_SUCCESS";
export const ADMIN_APPOINTMENT_CREATE_FAIL = "ADMIN_APPOINTMENT_CREATE_FAIL";
export const ADMIN_APPOINTMENT_CREATE_RESET = "ADMIN_APPOINTMENT_CREATE_RESET";

export const ADMIN_APPOINTMENT_SHOW_REQUEST = "ADMIN_APPOINTMENT_SHOW_REQUEST";
export const ADMIN_APPOINTMENT_SHOW_SUCCESS = "ADMIN_APPOINTMENT_SHOW_SUCCESS";
export const ADMIN_APPOINTMENT_SHOW_FAIL = "ADMIN_APPOINTMENT_SHOW_FAIL";
export const ADMIN_APPOINTMENT_SHOW_RESET = "ADMIN_APPOINTMENT_SHOW_RESET";

export const ADMIN_APPOINTMENT_SHOWSINGLE_REQUEST = "ADMIN_APPOINTMENT_SHOWSINGLE_REQUEST";
export const ADMIN_APPOINTMENT_SHOWSINGLE_SUCCESS = "ADMIN_APPOINTMENT_SHOWSINGLE_SUCCESS";
export const ADMIN_APPOINTMENT_SHOWSINGLE_FAIL = "ADMIN_APPOINTMENT_SHOWSINGLE_FAIL";
export const ADMIN_APPOINTMENT_SHOWSINGLE_RESET = "ADMIN_APPOINTMENT_SHOWSINGLE_RESET";

export const ADMIN_APPOINTMENT_DELETE_REQUEST = "ADMIN_APPOINTMENT_DELETE_REQUEST";
export const ADMIN_APPOINTMENT_DELETE_SUCCESS = "ADMIN_APPOINTMENT_DELETE_SUCCESS";
export const ADMIN_APPOINTMENT_DELETE_FAIL = "ADMIN_APPOINTMENT_DELETE_FAIL";
export const ADMIN_APPOINTMENT_DELETE_RESET = "ADMIN_APPOINTMENT_DELETE_RESET";

export const ADMIN_APPOINTMENT_UPDATE_REQUEST = "ADMIN_APPOINTMENT_UPDATE_REQUEST";
export const ADMIN_APPOINTMENT_UPDATE_SUCCESS = "ADMIN_APPOINTMENT_UPDATE_SUCCESS";
export const ADMIN_APPOINTMENT_UPDATE_FAIL = "ADMIN_APPOINTMENT_UPDATE_FAIL";
export const ADMIN_APPOINTMENT_UPDATE_RESET = "ADMIN_APPOINTMENT_UPDATE_RESET";