export const APPOINTMENT_CREATE_REQUEST = "APPOINTMENT_CREATE_REQUEST";
export const APPOINTMENT_CREATE_SUCCESS = "APPOINTMENT_CREATE_SUCCESS";
export const APPOINTMENT_CREATE_FAIL = "APPOINTMENT_CREATE_FAIL";
export const APPOINTMENT_CREATE_RESET = "APPOINTMENT_CREATE_RESET";

export const APPOINTMENT_SHOW_REQUEST = "APPOINTMENT_SHOW_REQUEST";
export const APPOINTMENT_SHOW_SUCCESS = "APPOINTMENT_SHOW_SUCCESS";
export const APPOINTMENT_SHOW_FAIL = "APPOINTMENT_SHOW_FAIL";
export const APPOINTMENT_SHOW_RESET = "APPOINTMENT_SHOW_RESET";

export const APPOINTMENT_SHOWSINGLE_REQUEST = "APPOINTMENT_SHOWSINGLE_REQUEST";
export const APPOINTMENT_SHOWSINGLE_SUCCESS = "APPOINTMENT_SHOWSINGLE_SUCCESS";
export const APPOINTMENT_SHOWSINGLE_FAIL = "APPOINTMENT_SHOWSINGLE_FAIL";
export const APPOINTMENT_SHOWSINGLE_RESET = "APPOINTMENT_SHOWSINGLE_RESET";

export const APPOINTMENT_DELETE_REQUEST = "APPOINTMENT_DELETE_REQUEST";
export const APPOINTMENT_DELETE_SUCCESS = "APPOINTMENT_DELETE_SUCCESS";
export const APPOINTMENT_DELETE_FAIL = "APPOINTMENT_DELETE_FAIL";
export const APPOINTMENT_DELETE_RESET = "APPOINTMENT_DELETE_RESET";

export const APPOINTMENT_UPDATE_REQUEST = "APPOINTMENT_UPDATE_REQUEST";
export const APPOINTMENT_UPDATE_SUCCESS = "APPOINTMENT_UPDATE_SUCCESS";
export const APPOINTMENT_UPDATE_FAIL = "APPOINTMENT_UPDATE_FAIL";
export const APPOINTMENT_UPDATE_RESET = "APPOINTMENT_UPDATE_RESET";